### ISSUE TITLE
Unexpected token (23:9)

### ISSUE THREAD

**Issue by abcnny** [landtechnologies/Mapbox-vector-tiles-basic-js-renderer#18]
when i run "npm run build-dev"，The error is as follows

`
> mapbox-gl@2.1.3 build-dev D:\job\opensource\vspace\Mapbox-vector-tiles-basic-js-renderer
> browserify src/index.js --debug  --ignore-transform unassertify --standalone mapboxgl > dist/mapbox-gl-dev.js && tap --no-coverage test/build/dev.test.js

---
19 :     + currentlyRenderingTiles - a list of tiles that we actually want to be able to paint
20 : */
21 :
22 : class BasicSourceCache {
23 :   _source;
              ^

Unexpected token (23:9)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mapbox-gl@2.1.3 build-dev: `browserify src/index.js --debug  --ignore-transform unassertify --standalone mapboxgl > dist/mapbox-gl-dev.js && tap --no-coverage test/build/dev.test.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mapbox-gl@2.1.3 build-dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2020-11-03T02_49_22_515Z-debug.log`

how would i fix it，thanks

**Comment by 3DGISKing** [comment]
I got the same error. did you fix?

**Comment by abcnny** [comment]
just run "webpack"

**Comment by 3DGISKing** [comment]
thanks. works.
